# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# サイト設定は、新しいサイトをパーソナライズするために使用されます。
# HTMLファイルを見てください、{{site.title}}、{{site.email }}などでアクセスできます。
# 好きなカスタム変数を作成することができ、テンプレートでは {{ site.myvariable }} でアクセスできます。

#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : "" # サイトの基本ホスト名とプロトコル（例：http://example.com
baseurl: "" # あなたのサイトのサブパス（例：/blog

title      : mming -ミング-
email      : mming.lab@gmail.com #これはまた、電子メールでのお問い合わせフォームの送信先でもあります。
phone   : "090-1234-5678"
address : "東京都港区南青山1-1-1"
description: "発達凸凹っ子専用クラスもある小さなプログラミング教室"
author     : mming -ミング-
# logo:     #任意、デフォルトはサイトタイトル
# path: assets\img\clients\creative-market.jpg
# height: 60 #px単位の高さ、デフォルトは52px

locale: "ja-JP" # _data/sitetext.ymlで利用可能な言語を参照してください。

analytics:
  google: #Googleアナリティクスのトラッキングコード

collections:
  portfolio:

markdown: kramdown

# FormspreeのフォームIDに基づくURLをメールベースのURLの代わりに使用するには、以下の行のコメントを外します。
# 詳細: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path： "f/a_form_id"

plugins:
  - jekyll-remote-theme
