# ========================================
# mmingプログラミング教室 - サイトコンテンツデータ設定
# 全体リファクタリング 2024年12月・重複データ整理済み
# ========================================
#
# 【このファイルの役割】
# サイト表示用のコンテンツデータを管理（サイト名、説明、連絡先等）
# Jekyll設定は _config.yml で管理し、役割を明確に分離
#
# 【使用方法】
# ここで設定した値は {{ site.data.config.設定名 }} でアクセスできます。
# 例: {{ site.data.config.site.name }} でサイト名を呼び出せます。
#
# 【_config.yml との役割分担】
# _config.yml: Jekyll動作設定（プラグイン、ビルド、SEO基本設定）
# _data/config.yml: サイト表示データ（名前、説明、連絡先、詳細情報）

# ========================================
# サイト基本情報
# ========================================
site:
  # サイト名（ヘッダーやタイトルタグに使用）
  name: "mming プログラミング教室"

  # 短縮名（ファビコンやソーシャルメディア用）
  short_name: "mming"

  # サイトのキャッチフレーズ（ヘッダー下部に表示）
  tagline: "特別な配慮が必要な子どものための専門教室"

  # サイトの説明文（SEOのdescriptionタグや構造化データに使用）
  description: "特別な配慮が必要な子ども向けのプログラミング教室。お子様の「好きなこと」「得意なこと」を大切に、一人ひとりの特性に合わせた指導を行います。"

  # サイト運営者名（著者情報やフッターに使用）
  author: "mming プログラミング教室"

  # サイトのベースURL（本番環境のURL）
  url: "https://mming-lab.github.io/"

  # 言語・地域設定（構造化データやメタタグに使用）
  locale: "ja_JP"

  # 注: timezone は _config.yml で管理（Jekyll設定のため重複削除）

  # SNSシェア用画像（og:imageタグに使用、1200x630px推奨）
  og_image: "/assets/images/site-assets/mming_ogp.webp"

  # サイトロゴ（ヘッダーに表示、40x40px推奨）
  logo: "/assets/images/logos/mmingロゴアイコン青.png"

# ========================================
# 連絡先情報
# ========================================
contact:
  # メールアドレス（問い合わせ用、構造化データに使用）
  email: "mming.lab＠gmail.com"

  # 電話番号（現在は非表示設定）
  # phone: ""  # 電話番号は表示しない

  # 住所情報（アクセスページや構造化データに使用）
  address:
    # 郵便番号
    postal_code: "892-0841"
    # 都道府県
    prefecture: "鹿児島県"
    # 市区町村
    city: "鹿児島市"
    # 番地・建物名
    street: "照国町２−１１ 第一天神ビル 1-D"
    # 完全な住所（表示用）
    full: "鹿児島市照国町２−１１ 第一天神ビル 1-D"

# ========================================
# SEO設定（検索エンジン最適化）
# ========================================
seo:
  # 検索キーワード（メタタグのkeywordsに使用）
  keywords:
    - "プログラミング教室" # メインキーワード
    - "発達障害" # ターゲット1
    - "ADHD" # ターゲット2
    - "ASL" # ターゲット3
    - "学習支援" # サービス内容1
    - "個別指導" # サービス内容2
    - "子ども" # 対象者
    - "適性チェック" # 独自サービス
    - "感覚過敏" # 特性
    - "発達特性" # 包括的キーワード

  # デフォルトのSNSシェア画像
  default_image: "/assets/images/site-assets/mming_ogp.webp"

  # 注: Twitter、Facebook、Google Analytics等の外部サービス設定は
  # 必要に応じて将来追加予定（現在は未使用のため削除）

  # 構造化データ設定（検索結果のリッチスニペット用）
  structured_data:
    # 組織タイプ（教育機関として認識される）
    type: "EducationalOrganization"
    # 価格帯表示（$$は中程度の価格帯を示す）
    price_range: "$$$$"

# ========================================
# 外部サービス連携設定
# ========================================
integrations:
  # Google Forms（問い合わせフォーム）
  google_forms:
    # 体験申込みフォームURL
    trial_application: "https://docs.google.com/forms/d/e/1FAIpQLSdpJMkKE6E3jgdn3uXRG1mxbPDXIUhHMaCSPmASvwjRuHvC9g/viewform"
    # お問い合わせフォームURL
    contact_form: "https://docs.google.com/forms/d/e/1FAIpQLScXEQViRPCFZ6kSRIc_pFx8tHfPEG9dGkiDTLsPPR0xdmo5Gg/viewform"
# ========================================
# 設定項目の使用方法
# ========================================
#
# このファイルの設定値は、サイト内で以下のように使用できます：
#
# HTML/Liquid テンプレート内で：
# - サイト名: {{ site.data.config.site.name }}
# - メールアドレス: {{ site.data.config.contact.email }}
# - ロゴ画像: {{ site.data.config.site.logo | relative_url }}
#
# 新しい設定を追加したい場合：
# 1. 適切なセクションに新しい項目を追加
# 2. HTMLテンプレートで {{ site.data.config.セクション.項目名 }} で呼び出し
# 3. 必要に応じてdefault.htmlやCSSでも参照可能
#
# 注意事項：
# - YAMLの構文に注意（インデントはスペース2個）
# - 文字列に特殊文字が含まれる場合は "" で囲む
# - リスト項目は - で始める
# - ファイル変更後はJekyllサーバーの再起動が必要
