#
# Work based on https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml
#

header:
  title: "mming -ミング-"
  text: "発達多様性の可能性を最大限に引き出すプログラミング教室"
  button: 詳しく
  buttonlink: "#services"


services:
  title: "教室の特徴"
  text: "発達多様性の可能性を最大限に引き出すための特徴"
  section: "services"
  striped: "no"
  list:
    - title: "特性に配慮した空間"
      desc: "光、音、触感に過敏な子どもたちのために、徹底的に環境を最適化しています。センサリースペース、個別スペース、ワークスペースを用意し、その日の状態に合わせて選べます。"
      icon: "fas fa-diagnoses"
    - title: "特性に合わせ教材をカスタム"
      desc: "識字や左右分別の困難さなど、お子様の特性に合わせ教育版マインクラフトに独自のカスタマイズを加えることでプログラミングや論理的思考の習得だけに専念できます。"
      icon: "fas fa-cubes"
    - title: "専門知識を持ったスタッフ"
      desc: "発達障害の知識と対応について専門的な学習を積んだスタッフが、お子様一人ひとりの特性に合わせて柔軟に対応します。"
      icon: "fas fa-user-friends"


about:
  title: "教室の方針"
  text: "子どもの学びと成長を支援する特別な教室"
  body: "「うちの子は教室に馴染めるだろうか？」「理解してもらえるだろうか？」そんな不安を抱えた保護者の方々へ。<br /><br />mming -ミング-は、発達多様性のお子様とその家族のために生まれた特別な教室です。<br />学校でも療育でもない、もう一つの居場所。ここでは、お子様の独自の才能や興味を大切にし、安心して自分らしく学べる環境を提供しています。<br />感覚過敏、コミュニケーションの難しさ、集中力の課題、これらは弱点ではなく、お子様の独自の特性です。私たちは、その特性を理解し、尊重し、最大限に活かすアプローチを心がけています。専門家でもある私たちが、お子様一人ひとりの困り感に寄り添い、個別最適化された学習環境を開発します。<br />お子様の追求心を育み、得意なことを伸ばすことに全力を注ぎ、自信と喜びを持って成長できるようサポートします。"
  section: "about"
  striped: "yes"


trial:
  title: "まずは教室の雰囲気を感じてみませんか？"
  text: "見学・無料体験は随時受付中です。お子様がリラックスできるよう、一度に1組ずつ体験教室を行っています。"
  button: "無料体験のお申込み"
  buttonlink: "https://forms.gle/xz8XFBwxpzadWekL7"
  section: "trial"
  striped: "no"


environment:
  title: "特性に配慮した空間"
  text: "光や音に敏感な子どもに配慮し空間を整え「 ワークスペース」「個別スペース」「リラックススペース」といった異なる空間を自由に行き来することで周囲の刺激を避けて集中したい日もあれば、みんなと一緒に取り組みたい日もある、といった毎日変化する子どもたちのコンディションに合わせて環境を選択できるサポートをします。"
  section: "environment"
  striped: "yes"
  instagram:
    - id: "DAsN1KWPrLn"
    - id: "DAnKU4PPq_-"
    - id: "DAnJ0dcv1tm"


team:
  title: "スタッフ"
  text: "専門知識を持ったスタッフが対応します。"
  section: "team"
  striped: "no"
  people:
    - name: "宮永　あかり"
      role: "<strong>代表</strong><br />発達障害当事者として、お子様と保護者の方の気持ちに寄り添った支援を心がけています。<br />発達障害児支援士<br />チャイルドカウンセラー<br />グラフィックデザイナー"
      image: assets/img/team/MIYANAGA_akari.jpg
      social:
        - url: https://www.instagram.com/akari_dekoboko/
          icon: "fab fa-instagram"
        # - url: https://www.facebook.com/profile.php?id=100089067379994
        #   icon: "fab fa-facebook-f"
    - name: "宮永　ともひさ"
      role: "<strong>メンター</strong><br />テクノロジーを通じて、子どもたちの学びを革新的にサポートします。<br />システムエンジニア<br />教育版マインクラフトアンバサダー<br />Minecraftカップ地区大会審査員(第5・6回)"
      image: assets/img/team/tomohisa_image.jpg
      social:
        - url: https://www.credly.com/badges/cd089180-e5f5-44bf-bb25-b3dafb703f8e/public_url
          icon: "assets/img/team/minecraft-education-ambassador.png"
        - url: https://twitter.com/Tomohisa_YUTARI
          icon: "fab fa-twitter"
        - url: https://www.instagram.com/miyanaga.tomohisa
          icon: "fab fa-instagram"
        - url: https://www.facebook.com/profile.php?id=100081525017355
          icon: "fab fa-facebook-f"



clients:
  section: "clients"
  striped: "yes"
  max-height: 50px
  horizontal-scrolling: "" #"yes/no"
  list:
    - title: "教育版マインクラフト"
      url: https://education.minecraft.net/ja-jp
      logo: https://education.minecraft.net/content/dam/education-edition/logos/education-minecraft-logo.png
    - title: "すらら"
      url: https://surala.jp/type/disability
      logo: https://surala.jp/images/common/logo.png
    - title: "Minecraftカップ"
      url: https://minecraftcup.com
      logo: https://minecraftcup.com/2022/wp-content/themes/minecraft/img/common/logo_2024.png
    # - title: "マルヤガーデンズ"
    #   url: https://www.maruya-gardens.com/
    #   logo: https://www.maruya-gardens.com/common/images/common/symbol.png
    - title: "じぶんらしい暮らしYUTAR"
      url: https://yutari.link
      logo: assets/img/clients/yutari-link.png


portfolio:
  title: "詳細情報"
  #text: "特徴の詳細を説明"
  section: "portfolio"
  striped: "no"
  closebutton: "閉じる"


contact:
  title: "アクセスガイド"
  # text: "こちらからお問い合わせください"
  map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d849.6343560674468!2d130.550142!3d31.591730599999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x353e6700584290b5%3A0x5a5528e333af3ae!2zbW1pbmcgLeODn-ODs-OCsC0!5e0!3m2!1sja!2sjp!4v1714606049903!5m2!1sja!2sjp"
  address: "鹿児島市照国町２−１１ 第一天神ビル 1-D<br />高見馬場電停から徒歩7分<br />山下小学校前バス停から徒歩4分<br />公共交通機関かコインパーキングをご利用ください。"
  striped: "yes"


inquiry:
  title: "お問合せ"
  forms: "https://docs.google.com/forms/d/e/1FAIpQLScXEQViRPCFZ6kSRIc_pFx8tHfPEG9dGkiDTLsPPR0xdmo5Gg/viewform?embedded=true"
  section: "inquiry"
  striped: "no"



footer:
  legal: "個人情報保護方針"
  striped: "yes"
  social:
    - url: "https://github.com/Mming-Lab"
      icon: "fab fa-github"
    - url: "https://www.instagram.com/mming.lab/"
      icon: "fab fa-instagram"
    # - url: https://line.me/ja/
    #   icon: "fab fa-line"
    # - url: https://twitter.com
    #   icon: "fab fa-twitter"
    # - url: https://facebook.com
    #   icon: "fab fa-facebook-f"
  terms: 
    title: "会員規約"
    file: "assets/pdf/会員規約.pdf"




timeline:
  title: "沿革"
  text: "タイムライン"
  section: タイムライン
  # left is the default
  #start_align: "left"
  events:
    - title: "ささやかな始まり"
      year: "2009-2011"
      desc: "顧客がアディピシングのプロセスに注意を払うことは非常に重要です。それらは、賢者の楽しみを時にはその全体を拒否するようなものであり、実際にどこからでも拒否されるべきものですが、それらはまた、それらを賞賛する人々の苦痛にも当てはまります。"
      image: assets/img/timeline/1.jpg
      alt:
    - title: "代理店の誕生"
      year: "2011年3月"
      desc: "顧客がアディピシングのプロセスに注意を払うことは非常に重要です。それらは、賢者の楽しみを時にはその全体を拒否するようなものであり、実際にどこからでも拒否されるべきものですが、それらはまた、それらを賞賛する人々の苦痛にも当てはまります。"
      image: assets/img/timeline/2.jpg
      alt:
    - title: "Jekyllテーマ作成"
      year: "2019"
      desc: "Ravi Riley は、Bootstrap ベースのテーマである Agency を Jekyll テーマに変換しました。Jekyll テーマは、Ruby gem として、またはリモートでインストールできます。詳細については、ドキュメントを参照してください"
      image: assets/img/timeline/3.jpg
      alt: image alt text
    - title: "タイトル"
      year: "2009-2011"
      desc: "ここにあるあなたの記述、**Markdown**は完全にサポートされています。"
      image: assets/img/timeline/4.jpg
      alt:
      # you can enforce the alignment
      align: right
  end: "私たちの<br>物語の<br>一部となりましょう！"



