#
# Work based on https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml
#

header:
  title: mming -ミング- にようこそ！
  text: "<strong>2027/07開校</strong><br />発達凸凹っ子専用のクラスもあるプログラミング教室です"
  button: 詳しく
  buttonlink: "#services"

services:
  title: "教材"
  text: "本校にはコースはなく、好きな教材を選んで学びます。教材へ変更しても追加料金はかかりません。"
  section: services
  list:
    - title: "toio（トイオ）"
      desc: "小さなキューブ型ロボットトイ・toio（トイオ）。toioへの命令カードを並べてプログラミングの基本構造(順次、分岐、反復)を学びます。"
      icon: fas fa-robot
    - title: "マインクラフト"
      desc: "教育版マインクラフトのコードビルダ機能をつかってプログラミングを学びます。エージェントという名のロボットにプログラミングで命令出来ます。ブロック、java script、pythonの3種類のプログラミング言語が使えます。"
      icon: fas fa-cube
    - title: "エキスパート"
      desc: "仕様書を読んで自分が作りたいアプリを作ります。プログラミング言語は自由です。"
      icon: fas fa-code

portfolio:
  title: "詳細情報"
  text: "教育版Minecraftのコンテンツの作成も承ります"
  section: portfolio
  closebutton: "閉じる"

timeline:
  title: "沿革"
  text: "Lorem ipsum timeline"
  section: timeline
  # left is the default
  #start_align: "left"
  events:
    - title: "Our Humble Beginnings"
      year: "2009-2011"
      desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
      image: assets/img/timeline/1.jpg
      alt:
    - title: "An Agency is Born"
      year: "March 2011"
      desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
      image: assets/img/timeline/2.jpg
      alt:
    - title: "Jekyll Theme is created"
      year: "2019"
      desc: "Ravi Riley converted Agency, a Bootstrap-based theme, into a Jekyll theme. The Jekyll theme can be installed as a Ruby gem, or remotely. For more information, visit the documentation."
      image: assets/img/timeline/3.jpg
      alt: image alt text
    - title: "Title"
      year: "2009-2011"
      desc: "Your description here, **Markdown** is fully supported."
      image: assets/img/timeline/4.jpg
      alt:
      # you can enforce the alignment
      align: right
  end: "Be Part <br> of Our <br> Story!"

about:
  title: "教室方針"
  text: "教室情報をここに書く。発達凸凹っ子が生きやすい"
  body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde. **Markdown** supported."
  section: about

team:
  title: "スタッフ"
  text: "メンターは変わり者"
  section: team
  people:
    - name: "宮永　あかり"
      role: "<strong>代表</strong><br />発達障害児支援士"
      image: assets/img/team/1.jpg
      social:
        - url: https://instagram.com
          icon: "fab fa-instagram"
        - url: https://www.facebook.com/dekobokokurashiakari
          icon: "fab fa-facebook-f"
    - name: "宮永　ともひさ"
      role: "<strong>メンター</strong><br />教育版マインクラフトアンバサダー<br />第5回Minecraftカップ地区大会審査員"
      image: assets/img/team/2.jpg
      social:
        - url: https://twitter.com/Tomohisa_YUTARI
          icon: "fab fa-twitter"
        - url: https://www.facebook.com/profile.php?id=100081525017355
          icon: "fab fa-facebook-f"

clients:
  section: clients
  max-height: 100px
  horizontal-scrolling: "" #"yes/no"
  list:
    - title: "envato"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/envato.jpg
    - title: "designmodo"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/designmodo.jpg
    - title: "themeforest"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/themeforest.jpg
    - title: "Creative Market"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/creative-market.jpg

contact:
  title: "お問合せ"
  text: "下記フォームまたは123456789までお電話ください。"
  section: contact
  name: "氏名*"
  name-validation: "あなたの氏名を入力してください。"
  email: "Eメール*"
  email-validation: "あなたのEメールを入力してください。"
  phone: "電話番号"
  phone-validation: "あなたの電話番号を入力してください。"
  message: "メッセージ*"
  message-validation: "メッセージを入力してください。"
  subject: "お問い合わせフォーム"
  submit: "メッセージ送信"
  c_address: "〒892-0841 鹿児島県鹿児島市照国町２−１１ 第一天神ビル 1-D"

footer:
  legal: "個人情報保護方針"
  social:
    - url: https://line.me/ja/
      icon: "fab fa-line"
    - url: https://github.com/Mming-Lab
      icon: "fab fa-github"
    - url: https://twitter.com
      icon: "fab fa-twitter"
    - url: https://facebook.com
      icon: "fab fa-facebook-f"
    - url: https://instagram.com
      icon: "fab fa-instagram"
